// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hiqohopbvlyvhnbvvtrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpcW9ob3Bidmx5dmhuYnZ2dHJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NzczNTksImV4cCI6MjA3NDM1MzM1OX0.xqbpSj_d_8Lu11VnSFSWXPjKQNI8WTT6k--UIRHFCnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});